// Sky data: bright stars, constellation lines, deep-sky objects (full Messier
// catalog), meteor showers, locations.
// RA in decimal hours, Dec in decimal degrees (J2000). mag = visual magnitude.
// Positions are chart-grade (rounded) — right for a finder map, not an ephemeris.

export const STARS = [
  // Ursa Major
  {id:"dubhe",   n:"Dubhe",   ra:11.062, dec:61.75, mag:1.79, con:"UMa"},
  {id:"merak",   n:"Merak",   ra:11.031, dec:56.38, mag:2.37, con:"UMa"},
  {id:"phecda",  n:"Phecda",  ra:11.897, dec:53.69, mag:2.44, con:"UMa"},
  {id:"megrez",  n:"Megrez",  ra:12.257, dec:57.03, mag:3.31, con:"UMa"},
  {id:"alioth",  n:"Alioth",  ra:12.900, dec:55.96, mag:1.77, con:"UMa"},
  {id:"mizar",   n:"Mizar",   ra:13.399, dec:54.93, mag:2.27, con:"UMa"},
  {id:"alkaid",  n:"Alkaid",  ra:13.792, dec:49.31, mag:1.86, con:"UMa"},
  // Ursa Minor
  {id:"polaris", n:"Polaris", ra:2.530,  dec:89.26, mag:1.98, con:"UMi"},
  {id:"kochab",  n:"Kochab",  ra:14.845, dec:74.16, mag:2.08, con:"UMi"},
  {id:"pherkad", n:"Pherkad", ra:15.345, dec:71.83, mag:3.05, con:"UMi"},
  {id:"yildun",  n:"Yildun",  ra:17.537, dec:86.59, mag:4.36, con:"UMi"},
  {id:"epsUMi",  n:"",        ra:16.766, dec:82.04, mag:4.23, con:"UMi"},
  {id:"zetUMi",  n:"",        ra:15.734, dec:77.79, mag:4.32, con:"UMi"},
  // Cassiopeia
  {id:"schedar", n:"Schedar", ra:0.675,  dec:56.54, mag:2.24, con:"Cas"},
  {id:"caph",    n:"Caph",    ra:0.153,  dec:59.15, mag:2.28, con:"Cas"},
  {id:"gamCas",  n:"Navi",    ra:0.945,  dec:60.72, mag:2.47, con:"Cas"},
  {id:"ruchbah", n:"Ruchbah", ra:1.430,  dec:60.24, mag:2.68, con:"Cas"},
  {id:"segin",   n:"Segin",   ra:1.907,  dec:63.67, mag:3.38, con:"Cas"},
  // Cepheus
  {id:"alderamin",n:"Alderamin",ra:21.309,dec:62.59,mag:2.45, con:"Cep"},
  {id:"alfirk",  n:"Alfirk",  ra:21.477, dec:70.56, mag:3.23, con:"Cep"},
  {id:"errai",   n:"Errai",   ra:23.656, dec:77.63, mag:3.21, con:"Cep"},
  // Orion
  {id:"betelgeuse",n:"Betelgeuse",ra:5.919,dec:7.41,mag:0.45, con:"Ori"},
  {id:"rigel",   n:"Rigel",   ra:5.242,  dec:-8.20, mag:0.18, con:"Ori"},
  {id:"bellatrix",n:"Bellatrix",ra:5.418,dec:6.35,  mag:1.64, con:"Ori"},
  {id:"mintaka", n:"Mintaka", ra:5.533,  dec:-0.30, mag:2.23, con:"Ori"},
  {id:"alnilam", n:"Alnilam", ra:5.604,  dec:-1.20, mag:1.69, con:"Ori"},
  {id:"alnitak", n:"Alnitak", ra:5.679,  dec:-1.94, mag:1.74, con:"Ori"},
  {id:"saiph",   n:"Saiph",   ra:5.796,  dec:-9.67, mag:2.07, con:"Ori"},
  // Canis Major
  {id:"sirius",  n:"Sirius",  ra:6.752,  dec:-16.72,mag:-1.44,con:"CMa"},
  {id:"adhara",  n:"Adhara",  ra:6.977,  dec:-28.97,mag:1.50, con:"CMa"},
  {id:"wezen",   n:"Wezen",   ra:7.140,  dec:-26.39,mag:1.83, con:"CMa"},
  {id:"mirzam",  n:"Mirzam",  ra:6.378,  dec:-17.96,mag:1.98, con:"CMa"},
  {id:"aludra",  n:"Aludra",  ra:7.401,  dec:-29.30,mag:2.45, con:"CMa"},
  // Canis Minor
  {id:"procyon", n:"Procyon", ra:7.655,  dec:5.22,  mag:0.40, con:"CMi"},
  {id:"gomeisa", n:"Gomeisa", ra:7.452,  dec:8.29,  mag:2.89, con:"CMi"},
  // Gemini
  {id:"castor",  n:"Castor",  ra:7.577,  dec:31.89, mag:1.58, con:"Gem"},
  {id:"pollux",  n:"Pollux",  ra:7.755,  dec:28.03, mag:1.16, con:"Gem"},
  {id:"alhena",  n:"Alhena",  ra:6.629,  dec:16.40, mag:1.93, con:"Gem"},
  {id:"tejat",   n:"Tejat",   ra:6.382,  dec:22.51, mag:2.87, con:"Gem"},
  {id:"mebsuta", n:"Mebsuta", ra:6.732,  dec:25.13, mag:3.06, con:"Gem"},
  // Taurus
  {id:"aldebaran",n:"Aldebaran",ra:4.599,dec:16.51, mag:0.87, con:"Tau"},
  {id:"elnath",  n:"Elnath",  ra:5.438,  dec:28.61, mag:1.65, con:"Tau"},
  {id:"alcyone", n:"Alcyone", ra:3.791,  dec:24.11, mag:2.87, con:"Tau"},
  {id:"gamTau",  n:"",        ra:4.330,  dec:15.63, mag:3.65, con:"Tau"},
  {id:"zetTau",  n:"",        ra:5.627,  dec:21.14, mag:2.97, con:"Tau"},
  // Auriga
  {id:"capella", n:"Capella", ra:5.278,  dec:45.998,mag:0.08, con:"Aur"},
  {id:"menkalinan",n:"Menkalinan",ra:5.992,dec:44.95,mag:1.90,con:"Aur"},
  {id:"thetaAur",n:"",        ra:5.995,  dec:37.21, mag:2.62, con:"Aur"},
  {id:"hassaleh",n:"Hassaleh",ra:4.950,  dec:33.17, mag:2.69, con:"Aur"},
  // Perseus
  {id:"mirfak",  n:"Mirfak",  ra:3.405,  dec:49.86, mag:1.79, con:"Per"},
  {id:"algol",   n:"Algol",   ra:3.136,  dec:40.96, mag:2.09, con:"Per"},
  {id:"gamPer",  n:"",        ra:3.080,  dec:53.51, mag:2.91, con:"Per"},
  {id:"delPer",  n:"",        ra:3.715,  dec:47.79, mag:3.01, con:"Per"},
  {id:"epsPer",  n:"",        ra:3.964,  dec:40.01, mag:2.90, con:"Per"},
  {id:"zetPer",  n:"",        ra:3.902,  dec:31.88, mag:2.85, con:"Per"},
  // Andromeda
  {id:"alpheratz",n:"Alpheratz",ra:0.139,dec:29.09, mag:2.06, con:"And"},
  {id:"mirach",  n:"Mirach",  ra:1.162,  dec:35.62, mag:2.05, con:"And"},
  {id:"almach",  n:"Almach",  ra:2.065,  dec:42.33, mag:2.10, con:"And"},
  {id:"delAnd",  n:"",        ra:0.655,  dec:30.86, mag:3.27, con:"And"},
  // Pegasus
  {id:"markab",  n:"Markab",  ra:23.079, dec:15.21, mag:2.49, con:"Peg"},
  {id:"scheat",  n:"Scheat",  ra:23.063, dec:28.08, mag:2.42, con:"Peg"},
  {id:"algenib", n:"Algenib", ra:0.220,  dec:15.18, mag:2.83, con:"Peg"},
  {id:"enif",    n:"Enif",    ra:21.736, dec:9.875, mag:2.39, con:"Peg"},
  // Aries
  {id:"hamal",   n:"Hamal",   ra:2.119,  dec:23.46, mag:2.00, con:"Ari"},
  {id:"sheratan",n:"Sheratan",ra:1.911,  dec:20.81, mag:2.64, con:"Ari"},
  {id:"mesarthim",n:"",       ra:1.892,  dec:19.29, mag:3.86, con:"Ari"},
  // Leo
  {id:"regulus", n:"Regulus", ra:10.139, dec:11.97, mag:1.36, con:"Leo"},
  {id:"denebola",n:"Denebola",ra:11.818, dec:14.57, mag:2.14, con:"Leo"},
  {id:"algieba", n:"Algieba", ra:10.333, dec:19.84, mag:2.21, con:"Leo"},
  {id:"zosma",   n:"Zosma",   ra:11.235, dec:20.52, mag:2.56, con:"Leo"},
  {id:"etaLeo",  n:"",        ra:10.122, dec:16.76, mag:3.49, con:"Leo"},
  {id:"chertan", n:"Chertan", ra:11.237, dec:15.43, mag:3.33, con:"Leo"},
  // Bootes
  {id:"arcturus",n:"Arcturus",ra:14.261, dec:19.18, mag:-0.05,con:"Boo"},
  {id:"izar",    n:"Izar",    ra:14.750, dec:27.07, mag:2.35, con:"Boo"},
  {id:"muphrid", n:"Muphrid", ra:13.911, dec:18.40, mag:2.68, con:"Boo"},
  {id:"seginus", n:"Seginus", ra:14.534, dec:38.31, mag:3.03, con:"Boo"},
  {id:"nekkar",  n:"Nekkar",  ra:15.032, dec:40.39, mag:3.49, con:"Boo"},
  {id:"delBoo",  n:"",        ra:15.258, dec:33.31, mag:3.47, con:"Boo"},
  // Corona Borealis
  {id:"alphecca",n:"Alphecca",ra:15.578, dec:26.71, mag:2.22, con:"CrB"},
  {id:"nusakan", n:"Nusakan", ra:15.464, dec:29.11, mag:3.66, con:"CrB"},
  {id:"gamCrB",  n:"",        ra:15.713, dec:26.30, mag:3.84, con:"CrB"},
  // Hercules
  {id:"kornephoros",n:"Kornephoros",ra:16.503,dec:21.49,mag:2.78,con:"Her"},
  {id:"zetHer",  n:"",        ra:16.688, dec:31.60, mag:2.81, con:"Her"},
  {id:"etaHer",  n:"",        ra:16.715, dec:38.92, mag:3.48, con:"Her"},
  {id:"piHer",   n:"",        ra:17.251, dec:36.81, mag:3.16, con:"Her"},
  {id:"epsHer",  n:"",        ra:17.005, dec:30.93, mag:3.92, con:"Her"},
  {id:"sarin",   n:"Sarin",   ra:17.251, dec:24.84, mag:3.12, con:"Her"},
  {id:"rasalgethi",n:"Rasalgethi",ra:17.244,dec:14.39,mag:3.10,con:"Her"},
  // Lyra
  {id:"vega",    n:"Vega",    ra:18.615, dec:38.78, mag:0.03, con:"Lyr"},
  {id:"sheliak", n:"Sheliak", ra:18.835, dec:33.36, mag:3.52, con:"Lyr"},
  {id:"sulafat", n:"Sulafat", ra:18.982, dec:32.69, mag:3.25, con:"Lyr"},
  {id:"delLyr",  n:"",        ra:18.908, dec:36.90, mag:4.30, con:"Lyr"},
  {id:"zetLyr",  n:"",        ra:18.746, dec:37.60, mag:4.36, con:"Lyr"},
  // Cygnus
  {id:"deneb",   n:"Deneb",   ra:20.690, dec:45.28, mag:1.25, con:"Cyg"},
  {id:"sadr",    n:"Sadr",    ra:20.370, dec:40.26, mag:2.23, con:"Cyg"},
  {id:"albireo", n:"Albireo", ra:19.512, dec:27.96, mag:3.18, con:"Cyg"},
  {id:"gienahCyg",n:"Gienah", ra:20.770, dec:33.97, mag:2.48, con:"Cyg"},
  {id:"delCyg",  n:"",        ra:19.749, dec:45.13, mag:2.87, con:"Cyg"},
  // Aquila
  {id:"altair",  n:"Altair",  ra:19.846, dec:8.87,  mag:0.76, con:"Aql"},
  {id:"tarazed", n:"Tarazed", ra:19.771, dec:10.61, mag:2.72, con:"Aql"},
  {id:"alshain", n:"Alshain", ra:19.922, dec:6.41,  mag:3.71, con:"Aql"},
  {id:"delAql",  n:"",        ra:19.425, dec:3.115, mag:3.36, con:"Aql"},
  {id:"zetAql",  n:"",        ra:19.090, dec:13.86, mag:2.99, con:"Aql"},
  {id:"thetaAql",n:"",        ra:20.188, dec:-0.82, mag:3.23, con:"Aql"},
  {id:"lamAql",  n:"",        ra:19.104, dec:-4.88, mag:3.43, con:"Aql"},
  // Ophiuchus
  {id:"rasalhague",n:"Rasalhague",ra:17.582,dec:12.56,mag:2.08,con:"Oph"},
  {id:"cebalrai",n:"Cebalrai",ra:17.724, dec:4.57,  mag:2.76, con:"Oph"},
  {id:"yedPrior",n:"Yed Prior",ra:16.239,dec:-3.69, mag:2.74, con:"Oph"},
  {id:"zetOph",  n:"",        ra:16.620, dec:-10.57,mag:2.56, con:"Oph"},
  {id:"etaOph",  n:"",        ra:17.173, dec:-15.72,mag:2.43, con:"Oph"},
  {id:"kapOph",  n:"",        ra:16.961, dec:9.38,  mag:3.20, con:"Oph"},
  // Draco
  {id:"eltanin", n:"Eltanin", ra:17.943, dec:51.49, mag:2.23, con:"Dra"},
  {id:"rastaban",n:"Rastaban",ra:17.507, dec:52.30, mag:2.79, con:"Dra"},
  {id:"grumium", n:"Grumium", ra:17.892, dec:56.87, mag:3.75, con:"Dra"},
  {id:"delDra",  n:"",        ra:19.209, dec:67.66, mag:3.07, con:"Dra"},
  {id:"zetDra",  n:"",        ra:17.146, dec:65.71, mag:3.17, con:"Dra"},
  {id:"edasich", n:"Edasich", ra:15.415, dec:58.97, mag:3.29, con:"Dra"},
  // Scorpius
  {id:"antares", n:"Antares", ra:16.490, dec:-26.43,mag:1.06, con:"Sco"},
  {id:"graffias",n:"Graffias",ra:16.090, dec:-19.81,mag:2.56, con:"Sco"},
  {id:"dschubba",n:"Dschubba",ra:16.005, dec:-22.62,mag:2.29, con:"Sco"},
  {id:"piSco",   n:"",        ra:15.981, dec:-26.11,mag:2.89, con:"Sco"},
  {id:"tauSco",  n:"",        ra:16.598, dec:-28.22,mag:2.82, con:"Sco"},
  {id:"epsSco",  n:"",        ra:16.836, dec:-34.29,mag:2.29, con:"Sco"},
  {id:"muSco",   n:"",        ra:16.864, dec:-38.05,mag:3.00, con:"Sco"},
  {id:"sargas",  n:"Sargas",  ra:17.622, dec:-42.99,mag:1.87, con:"Sco"},
  {id:"shaula",  n:"Shaula",  ra:17.560, dec:-37.10,mag:1.62, con:"Sco"},
  {id:"lesath",  n:"Lesath",  ra:17.512, dec:-37.30,mag:2.69, con:"Sco"},
  // Sagittarius (Teapot)
  {id:"kausAustralis",n:"Kaus Australis",ra:18.403,dec:-34.38,mag:1.79,con:"Sgr"},
  {id:"nunki",   n:"Nunki",   ra:18.921, dec:-26.30,mag:2.05, con:"Sgr"},
  {id:"kausMedia",n:"Kaus Media",ra:18.350,dec:-29.83,mag:2.70,con:"Sgr"},
  {id:"kausBorealis",n:"Kaus Borealis",ra:18.466,dec:-25.42,mag:2.81,con:"Sgr"},
  {id:"alnasl",  n:"Alnasl",  ra:18.097, dec:-30.42,mag:2.99, con:"Sgr"},
  {id:"phiSgr",  n:"",        ra:18.764, dec:-26.99,mag:3.17, con:"Sgr"},
  {id:"zetSgr",  n:"",        ra:19.044, dec:-29.88,mag:2.60, con:"Sgr"},
  {id:"tauSgr",  n:"",        ra:19.115, dec:-27.67,mag:3.32, con:"Sgr"},
  // Virgo / Spica
  {id:"spica",   n:"Spica",   ra:13.420, dec:-11.16,mag:0.98, con:"Vir"},
  // Libra
  {id:"zubeneschamali",n:"Zubeneschamali",ra:15.283,dec:-9.38,mag:2.61,con:"Lib"},
  {id:"zubenelgenubi",n:"Zubenelgenubi",ra:14.848,dec:-16.04,mag:2.75,con:"Lib"},
  // Aquarius
  {id:"sadalsuud",n:"Sadalsuud",ra:21.526,dec:-5.57,mag:2.90,con:"Aqr"},
  {id:"sadalmelik",n:"Sadalmelik",ra:22.096,dec:-0.32,mag:2.95,con:"Aqr"},
  {id:"skat",    n:"Skat",    ra:22.911, dec:-15.82,mag:3.27, con:"Aqr"},
  // Capricornus
  {id:"denebAlgedi",n:"Deneb Algedi",ra:21.784,dec:-16.13,mag:2.85,con:"Cap"},
  {id:"dabih",   n:"Dabih",   ra:20.350, dec:-14.78,mag:3.05, con:"Cap"},
  {id:"algedi",  n:"Algedi",  ra:20.300, dec:-12.51,mag:3.57, con:"Cap"},
  {id:"gamCap",  n:"",        ra:21.668, dec:-16.66,mag:3.68, con:"Cap"},
  // Corvus
  {id:"gienahCrv",n:"Gienah", ra:12.263, dec:-17.54,mag:2.59, con:"Crv"},
  {id:"betCrv",  n:"",        ra:12.573, dec:-23.40,mag:2.65, con:"Crv"},
  {id:"algorab", n:"Algorab", ra:12.498, dec:-16.52,mag:2.95, con:"Crv"},
  {id:"epsCrv",  n:"",        ra:12.168, dec:-22.62,mag:3.02, con:"Crv"},
  // Bright loners
  {id:"fomalhaut",n:"Fomalhaut",ra:22.961,dec:-29.62,mag:1.16,con:"PsA"},
  {id:"alphard", n:"Alphard", ra:9.460,  dec:-8.66, mag:1.98, con:"Hya"},
  {id:"diphda",  n:"Diphda",  ra:0.726,  dec:-17.99,mag:2.04, con:"Cet"},
  {id:"menkar",  n:"Menkar",  ra:3.038,  dec:4.09,  mag:2.54, con:"Cet"},
  // Southern (below horizon from Belgium, included for completeness)
  {id:"acrux",   n:"Acrux",   ra:12.443, dec:-63.10,mag:0.77, con:"Cru"},
  {id:"mimosa",  n:"Mimosa",  ra:12.795, dec:-59.69,mag:1.25, con:"Cru"},
  {id:"gacrux",  n:"Gacrux",  ra:12.519, dec:-57.11,mag:1.59, con:"Cru"},
  {id:"delCru",  n:"",        ra:12.252, dec:-58.75,mag:2.79, con:"Cru"},
  {id:"rigilKent",n:"Rigil Kentaurus",ra:14.660,dec:-60.83,mag:-0.27,con:"Cen"},
  {id:"hadar",   n:"Hadar",   ra:14.064, dec:-60.37,mag:0.61, con:"Cen"},
  {id:"canopus", n:"Canopus", ra:6.399,  dec:-52.70,mag:-0.62,con:"Car"},
  {id:"achernar",n:"Achernar",ra:1.629,  dec:-57.24,mag:0.45, con:"Eri"},
  // --- Messier-country fill-ins (chart-grade J2000 positions) ---
  // Virgo
  {id:"porrima", n:"Porrima", ra:12.694, dec:-1.45, mag:2.74, con:"Vir"},
  {id:"vindemiatrix",n:"Vindemiatrix",ra:13.036,dec:10.96,mag:2.85,con:"Vir"},
  {id:"auva",    n:"Auva",    ra:12.927, dec:3.40,  mag:3.38, con:"Vir"},
  {id:"zavijava",n:"Zavijava",ra:11.845, dec:1.76,  mag:3.61, con:"Vir"},
  {id:"heze",    n:"Heze",    ra:13.578, dec:-0.60, mag:3.37, con:"Vir"},
  {id:"etaVir",  n:"",        ra:12.332, dec:-0.67, mag:3.89, con:"Vir"},
  // Cancer
  {id:"acubens", n:"Acubens", ra:8.975,  dec:11.86, mag:4.26, con:"Cnc"},
  {id:"asellusBor",n:"Asellus Borealis",ra:8.721,dec:21.47,mag:4.66,con:"Cnc"},
  {id:"asellusAus",n:"Asellus Australis",ra:8.745,dec:18.15,mag:3.94,con:"Cnc"},
  {id:"tarf",    n:"Tarf",    ra:8.275,  dec:9.19,  mag:3.53, con:"Cnc"},
  {id:"iotCnc",  n:"",        ra:8.778,  dec:28.76, mag:4.03, con:"Cnc"},
  // Canes Venatici
  {id:"corCaroli",n:"Cor Caroli",ra:12.934,dec:38.32,mag:2.89,con:"CVn"},
  {id:"chara",   n:"Chara",   ra:12.562, dec:41.36, mag:4.24, con:"CVn"},
  // Coma Berenices
  {id:"alfCom",  n:"Diadem",  ra:13.166, dec:17.53, mag:4.32, con:"Com"},
  {id:"betCom",  n:"",        ra:13.198, dec:27.88, mag:4.26, con:"Com"},
  {id:"gamCom",  n:"",        ra:12.449, dec:28.27, mag:4.36, con:"Com"},
  // Scutum
  {id:"alfSct",  n:"",        ra:18.587, dec:-8.24, mag:3.85, con:"Sct"},
  {id:"betSct",  n:"",        ra:18.786, dec:-4.75, mag:4.22, con:"Sct"},
  // Sagitta (the arrow that points the way to M27)
  {id:"gamSge",  n:"",        ra:19.979, dec:19.49, mag:3.51, con:"Sge"},
  {id:"delSge",  n:"",        ra:19.789, dec:18.53, mag:3.68, con:"Sge"},
  {id:"alfSge",  n:"Sham",    ra:19.668, dec:18.01, mag:4.39, con:"Sge"},
  {id:"betSge",  n:"",        ra:19.684, dec:17.48, mag:4.39, con:"Sge"},
  // Delphinus
  {id:"sualocin",n:"Sualocin",ra:20.661, dec:15.91, mag:3.77, con:"Del"},
  {id:"rotanev", n:"Rotanev", ra:20.626, dec:14.60, mag:3.62, con:"Del"},
  {id:"gamDel",  n:"",        ra:20.777, dec:16.12, mag:4.27, con:"Del"},
  {id:"delDel",  n:"",        ra:20.724, dec:15.07, mag:4.43, con:"Del"},
  {id:"epsDel",  n:"",        ra:20.553, dec:11.30, mag:4.03, con:"Del"},
  // Triangulum
  {id:"mothallah",n:"Mothallah",ra:1.885,dec:29.58, mag:3.42, con:"Tri"},
  {id:"betTri",  n:"",        ra:2.159,  dec:34.99, mag:3.00, con:"Tri"},
  {id:"gamTri",  n:"",        ra:2.289,  dec:33.85, mag:4.03, con:"Tri"},
  // Pisces (the knot + the two cords)
  {id:"alrescha",n:"Alrescha",ra:2.034,  dec:2.76,  mag:3.82, con:"Psc"},
  {id:"etaPsc",  n:"",        ra:1.525,  dec:15.35, mag:3.62, con:"Psc"},
  {id:"gamPsc",  n:"",        ra:23.286, dec:3.28,  mag:3.70, con:"Psc"},
  // Cetus (completing the whale)
  {id:"batenKaitos",n:"Baten Kaitos",ra:1.858,dec:-10.34,mag:3.74,con:"Cet"},
  {id:"gamCet",  n:"",        ra:2.722,  dec:3.24,  mag:3.47, con:"Cet"},
  // Hydra (the head, linking down to Alphard)
  {id:"zetHya",  n:"",        ra:8.923,  dec:5.95,  mag:3.11, con:"Hya"},
  {id:"epsHya",  n:"",        ra:8.780,  dec:6.42,  mag:3.38, con:"Hya"},
  // Lepus (under Orion)
  {id:"arneb",   n:"Arneb",   ra:5.545,  dec:-17.82,mag:2.58, con:"Lep"},
  {id:"nihal",   n:"Nihal",   ra:5.471,  dec:-20.76,mag:2.81, con:"Lep"},
  {id:"muLep",   n:"",        ra:5.216,  dec:-16.21,mag:3.29, con:"Lep"},
  {id:"epsLep",  n:"",        ra:5.091,  dec:-22.37,mag:3.19, con:"Lep"},
  // Serpens (Caput — hosts M5)
  {id:"unukalhai",n:"Unukalhai",ra:15.738,dec:6.43, mag:2.63, con:"Ser"},
  {id:"betSer",  n:"",        ra:15.770, dec:15.42, mag:3.65, con:"Ser"},
  {id:"muSer",   n:"",        ra:15.827, dec:-3.43, mag:3.54, con:"Ser"},
];

export const CONSTELLATIONS = {
  UMa:{name:"Ursa Major",lines:[["dubhe","merak"],["merak","phecda"],["phecda","megrez"],["megrez","dubhe"],["megrez","alioth"],["alioth","mizar"],["mizar","alkaid"]]},
  UMi:{name:"Ursa Minor",lines:[["polaris","yildun"],["yildun","epsUMi"],["epsUMi","zetUMi"],["zetUMi","kochab"],["kochab","pherkad"],["pherkad","epsUMi"]]},
  Cas:{name:"Cassiopeia",lines:[["caph","schedar"],["schedar","gamCas"],["gamCas","ruchbah"],["ruchbah","segin"]]},
  Cep:{name:"Cepheus",lines:[["alderamin","alfirk"],["alfirk","errai"],["errai","alderamin"]]},
  Ori:{name:"Orion",lines:[["bellatrix","betelgeuse"],["bellatrix","mintaka"],["betelgeuse","alnitak"],["mintaka","alnilam"],["alnilam","alnitak"],["mintaka","rigel"],["alnitak","saiph"],["rigel","saiph"]]},
  CMa:{name:"Canis Major",lines:[["sirius","mirzam"],["sirius","wezen"],["wezen","adhara"],["wezen","aludra"]]},
  CMi:{name:"Canis Minor",lines:[["procyon","gomeisa"]]},
  Gem:{name:"Gemini",lines:[["castor","pollux"],["castor","mebsuta"],["mebsuta","tejat"],["pollux","alhena"]]},
  Tau:{name:"Taurus",lines:[["elnath","aldebaran"],["aldebaran","gamTau"],["zetTau","aldebaran"]]},
  Aur:{name:"Auriga",lines:[["capella","menkalinan"],["menkalinan","thetaAur"],["thetaAur","elnath"],["elnath","hassaleh"],["hassaleh","capella"]]},
  Per:{name:"Perseus",lines:[["gamPer","mirfak"],["mirfak","delPer"],["delPer","algol"],["mirfak","epsPer"],["epsPer","zetPer"]]},
  And:{name:"Andromeda",lines:[["alpheratz","delAnd"],["delAnd","mirach"],["mirach","almach"]]},
  Peg:{name:"Pegasus",lines:[["markab","scheat"],["scheat","alpheratz"],["alpheratz","algenib"],["algenib","markab"],["markab","enif"]]},
  Ari:{name:"Aries",lines:[["hamal","sheratan"],["sheratan","mesarthim"]]},
  Leo:{name:"Leo",lines:[["regulus","etaLeo"],["etaLeo","algieba"],["algieba","zosma"],["zosma","denebola"],["denebola","chertan"],["chertan","regulus"],["zosma","chertan"]]},
  Boo:{name:"Boötes",lines:[["arcturus","muphrid"],["arcturus","izar"],["izar","delBoo"],["delBoo","nekkar"],["nekkar","seginus"],["seginus","arcturus"]]},
  CrB:{name:"Corona Borealis",lines:[["nusakan","alphecca"],["alphecca","gamCrB"]]},
  Her:{name:"Hercules",lines:[["zetHer","etaHer"],["etaHer","piHer"],["piHer","epsHer"],["epsHer","zetHer"],["kornephoros","zetHer"],["sarin","epsHer"],["kornephoros","rasalgethi"]]},
  Lyr:{name:"Lyra",lines:[["vega","sheliak"],["sheliak","sulafat"],["sulafat","delLyr"],["delLyr","zetLyr"],["zetLyr","sheliak"],["zetLyr","vega"]]},
  Cyg:{name:"Cygnus",lines:[["deneb","sadr"],["sadr","albireo"],["sadr","gienahCyg"],["sadr","delCyg"]]},
  Aql:{name:"Aquila",lines:[["zetAql","tarazed"],["tarazed","altair"],["altair","alshain"],["altair","delAql"],["altair","thetaAql"],["delAql","lamAql"]]},
  Oph:{name:"Ophiuchus",lines:[["rasalhague","kapOph"],["kapOph","yedPrior"],["yedPrior","zetOph"],["zetOph","etaOph"],["etaOph","cebalrai"],["cebalrai","rasalhague"]]},
  Dra:{name:"Draco",lines:[["eltanin","rastaban"],["rastaban","grumium"],["grumium","eltanin"],["eltanin","delDra"],["delDra","zetDra"],["zetDra","edasich"]]},
  Sco:{name:"Scorpius",lines:[["graffias","dschubba"],["dschubba","piSco"],["dschubba","antares"],["antares","tauSco"],["tauSco","epsSco"],["epsSco","muSco"],["muSco","sargas"],["sargas","shaula"],["shaula","lesath"]]},
  Sgr:{name:"Sagittarius",lines:[["alnasl","kausMedia"],["kausMedia","kausAustralis"],["kausAustralis","zetSgr"],["zetSgr","nunki"],["nunki","kausBorealis"],["kausBorealis","kausMedia"],["nunki","tauSgr"],["tauSgr","phiSgr"],["phiSgr","zetSgr"]]},
  Lib:{name:"Libra",lines:[["zubenelgenubi","zubeneschamali"]]},
  Aqr:{name:"Aquarius",lines:[["sadalsuud","sadalmelik"],["sadalmelik","skat"]]},
  Cap:{name:"Capricornus",lines:[["algedi","dabih"],["dabih","denebAlgedi"],["denebAlgedi","gamCap"],["gamCap","dabih"]]},
  Crv:{name:"Corvus",lines:[["epsCrv","gienahCrv"],["gienahCrv","algorab"],["algorab","betCrv"],["betCrv","epsCrv"]]},
  Cru:{name:"Crux",lines:[["acrux","gacrux"],["mimosa","delCru"]]},
  Cen:{name:"Centaurus",lines:[["rigilKent","hadar"]]},
  Vir:{name:"Virgo",lines:[["zavijava","etaVir"],["etaVir","porrima"],["porrima","auva"],["auva","vindemiatrix"],["porrima","heze"],["heze","spica"]]},
  Cnc:{name:"Cancer",lines:[["iotCnc","asellusBor"],["asellusBor","asellusAus"],["asellusAus","acubens"],["asellusAus","tarf"]]},
  CVn:{name:"Canes Venatici",lines:[["corCaroli","chara"]]},
  Com:{name:"Coma Berenices",lines:[["alfCom","betCom"],["betCom","gamCom"]]},
  Sct:{name:"Scutum",lines:[["alfSct","betSct"]]},
  Sge:{name:"Sagitta",lines:[["gamSge","delSge"],["delSge","alfSge"],["delSge","betSge"]]},
  Del:{name:"Delphinus",lines:[["sualocin","gamDel"],["gamDel","delDel"],["delDel","rotanev"],["rotanev","sualocin"],["rotanev","epsDel"]]},
  Tri:{name:"Triangulum",lines:[["mothallah","betTri"],["betTri","gamTri"],["gamTri","mothallah"]]},
  Psc:{name:"Pisces",lines:[["alrescha","etaPsc"],["alrescha","gamPsc"]]},
  Cet:{name:"Cetus",lines:[["menkar","gamCet"],["gamCet","batenKaitos"],["batenKaitos","diphda"]]},
  Hya:{name:"Hydra",lines:[["epsHya","zetHya"],["zetHya","alphard"]]},
  Lep:{name:"Lepus",lines:[["arneb","nihal"],["arneb","muLep"],["nihal","epsLep"]]},
  Ser:{name:"Serpens",lines:[["betSer","unukalhai"],["unukalhai","muSer"]]},
};

// Deep-sky objects: the complete Messier catalog (M1–M110) + a bonus showpiece.
// type: galaxy | nebula | planetary | globular | open
// Positions are chart-grade J2000 (fine for a finder map, not ephemeris-grade).
export const DSO = [
  {id:"M1",  n:"Crab Nebula",         ra:5.575,  dec:22.02, mag:8.4, type:"nebula",    con:"Tau", note:"A supernova remnant from 1054 AD — a faint smudge near Zeta Tauri; averted vision helps."},
  {id:"M2",  n:"M2 (globular)",       ra:21.558, dec:-0.82, mag:6.5, type:"globular",  con:"Aqr", note:"A bright, compact autumn globular — dense core, resolves at high power."},
  {id:"M3",  n:"M3 (globular)",       ra:13.703, dec:28.38, mag:6.2, type:"globular",  con:"CVn", note:"A bright, compact globular cluster, well placed in spring. Begins to resolve into stars at 200mm."},
  {id:"M4",  n:"M4 (globular)",       ra:16.393, dec:-26.53,mag:5.9, type:"globular",  con:"Sco", note:"A loose globular right beside Antares — easy to find, low in the south."},
  {id:"M5",  n:"M5 (globular)",       ra:15.310, dec:2.08,  mag:5.7, type:"globular",  con:"Ser", note:"One of the finest globulars — many call it M13's rival. Superb at 150–200×."},
  {id:"M6",  n:"Butterfly Cluster",   ra:17.668, dec:-32.22,mag:4.2, type:"open",       con:"Sco", note:"A bright open cluster shaped like a butterfly; very low from Belgium — needs a clear south horizon."},
  {id:"M7",  n:"Ptolemy's Cluster",   ra:17.898, dec:-34.79,mag:3.3, type:"open",       con:"Sco", note:"Naked-eye from the south; barely clears a Belgian horizon at culmination."},
  {id:"M8",  n:"Lagoon Nebula",       ra:18.060, dec:-24.38,mag:6.0, type:"nebula",    con:"Sgr", note:"A bright summer nebula with an embedded star cluster. Low in the south from Belgium — catch it at culmination."},
  {id:"M9",  n:"M9 (globular)",       ra:17.320, dec:-18.52,mag:7.9, type:"globular",  con:"Oph", note:"A small globular near the Ophiuchus 'foot'; a fuzzy ball at medium power."},
  {id:"M10", n:"M10 (globular)",      ra:16.953, dec:-4.10, mag:6.6, type:"globular",  con:"Oph", note:"A fine summer globular, pairs with nearby M12 — compare their densities."},
  {id:"M11", n:"Wild Duck Cluster",   ra:18.851, dec:-6.27, mag:6.3, type:"open",       con:"Sct", note:"A dense, rich open cluster shaped like a flight of ducks. A treat at medium power."},
  {id:"M12", n:"M12 (globular)",      ra:16.787, dec:-1.95, mag:6.7, type:"globular",  con:"Oph", note:"A looser globular than its neighbour M10 — resolves more easily."},
  {id:"M13", n:"Hercules Cluster",    ra:16.695, dec:36.46, mag:5.8, type:"globular",  con:"Her", note:"The finest globular cluster of the northern sky — hundreds of thousands of stars. A 200mm scope resolves its edges into pinpoints."},
  {id:"M14", n:"M14 (globular)",      ra:17.626, dec:-3.25, mag:7.6, type:"globular",  con:"Oph", note:"A smooth, unresolved glow in most amateur scopes — subtle but findable."},
  {id:"M15", n:"M15 (globular)",      ra:21.500, dec:12.17, mag:6.2, type:"globular",  con:"Peg", note:"A very dense globular near Pegasus with an intensely bright core."},
  {id:"M16", n:"Eagle Nebula",        ra:18.313, dec:-13.78,mag:6.0, type:"nebula",    con:"Ser", note:"Star cluster in glowing gas — home of the Pillars of Creation (the pillars need photos)."},
  {id:"M17", n:"Omega / Swan Nebula", ra:18.346, dec:-16.18,mag:6.0, type:"nebula",    con:"Sgr", note:"A bright checkmark-shaped nebula — one of summer's best; a UHC filter helps."},
  {id:"M18", n:"M18 (open cluster)",  ra:18.332, dec:-17.10,mag:6.9, type:"open",       con:"Sgr", note:"A small, sparse open cluster between M17 and M24."},
  {id:"M19", n:"M19 (globular)",      ra:17.043, dec:-26.27,mag:6.8, type:"globular",  con:"Oph", note:"A noticeably oval globular, low toward the galactic centre."},
  {id:"M20", n:"Trifid Nebula",       ra:18.045, dec:-23.03,mag:6.3, type:"nebula",    con:"Sgr", note:"Emission + reflection nebula split by dark lanes; just above the Lagoon."},
  {id:"M21", n:"M21 (open cluster)",  ra:18.076, dec:-22.50,mag:5.9, type:"open",       con:"Sgr", note:"A compact little cluster next to the Trifid — same low-power field."},
  {id:"M22", n:"Sagittarius Cluster", ra:18.608, dec:-23.90,mag:5.1, type:"globular",  con:"Sgr", note:"One of the brightest globular clusters, rivalling M13. Sits low toward the galactic centre."},
  {id:"M23", n:"M23 (open cluster)",  ra:17.949, dec:-19.02,mag:5.5, type:"open",       con:"Sgr", note:"A rich field of ~150 stars, lovely at low power."},
  {id:"M24", n:"Sagittarius Star Cloud",ra:18.280,dec:-18.55,mag:4.6,type:"open",       con:"Sgr", note:"Not a cluster but a window through the dust into the galaxy — a Milky Way highlight in binoculars."},
  {id:"M25", n:"M25 (open cluster)",  ra:18.529, dec:-19.25,mag:4.6, type:"open",       con:"Sgr", note:"Bright, loose cluster; fine in any small scope."},
  {id:"M26", n:"M26 (open cluster)",  ra:18.755, dec:-9.40, mag:8.0, type:"open",       con:"Sct", note:"A modest cluster in Scutum, overshadowed by nearby M11."},
  {id:"M27", n:"Dumbbell Nebula",     ra:19.994, dec:22.72, mag:7.4, type:"planetary", con:"Vul", note:"A large, bright planetary nebula shaped like an apple core or bow-tie. One of the easiest of its kind."},
  {id:"M28", n:"M28 (globular)",      ra:18.409, dec:-24.87,mag:6.8, type:"globular",  con:"Sgr", note:"A small globular just above the Teapot's lid star."},
  {id:"M29", n:"M29 (open cluster)",  ra:20.399, dec:38.52, mag:6.6, type:"open",       con:"Cyg", note:"A little box of stars near Sadr — small but easy."},
  {id:"M30", n:"M30 (globular)",      ra:21.673, dec:-23.18,mag:7.2, type:"globular",  con:"Cap", note:"A condensed autumn globular with star chains radiating from the core."},
  {id:"M31", n:"Andromeda Galaxy",    ra:0.712,  dec:41.27, mag:3.4, type:"galaxy",    con:"And", note:"The nearest big spiral galaxy, 2.5 million light-years away. A large, soft oval glow; its two companion galaxies are visible too."},
  {id:"M32", n:"M32 (companion of M31)",ra:0.712,dec:40.87, mag:8.1, type:"galaxy",    con:"And", note:"M31's compact elliptical companion — a small round glow right beside the great spiral."},
  {id:"M33", n:"Triangulum Galaxy",   ra:1.564,  dec:30.66, mag:5.7, type:"galaxy",    con:"Tri", note:"A big face-on spiral — very diffuse; needs dark skies and low power."},
  {id:"M34", n:"M34 (open cluster)",  ra:2.702,  dec:42.78, mag:5.2, type:"open",       con:"Per", note:"A coarse, bright cluster between Algol and Almach; fine at low power."},
  {id:"M35", n:"M35 (open cluster)",  ra:6.151,  dec:24.34, mag:5.3, type:"open",       con:"Gem", note:"A large, bright open cluster at the foot of Gemini, lovely at low power."},
  {id:"M36", n:"M36 (open cluster)",  ra:5.605,  dec:34.14, mag:6.0, type:"open",       con:"Aur", note:"One of Auriga's trio of clusters — the tightest of the three."},
  {id:"M37", n:"M37 (open cluster)",  ra:5.873,  dec:32.55, mag:5.6, type:"open",       con:"Aur", note:"The richest of Auriga's trio — a salt-spill of faint stars with an orange gem at centre."},
  {id:"M38", n:"M38 (open cluster)",  ra:5.478,  dec:35.85, mag:6.4, type:"open",       con:"Aur", note:"The third Auriga cluster, showing a rough pi shape."},
  {id:"M39", n:"M39 (open cluster)",  ra:21.530, dec:48.43, mag:4.6, type:"open",       con:"Cyg", note:"A big, loose triangle of stars NE of Deneb — binocular-friendly."},
  {id:"M40", n:"M40 (Winnecke 4)",    ra:12.373, dec:58.08, mag:8.4, type:"open",       con:"UMa", note:"Messier's oddity: just a faint double star. Bag it for the checklist."},
  {id:"M41", n:"M41 (open cluster)",  ra:6.767,  dec:-20.76,mag:4.5, type:"open",       con:"CMa", note:"A bright cluster 4° south of Sirius — easy hop, nice colour contrasts."},
  {id:"M42", n:"Orion Nebula",        ra:5.588,  dec:-5.39, mag:4.0, type:"nebula",    con:"Ori", note:"A glowing stellar nursery — the showpiece of winter. Bright even from the suburbs; look for the Trapezium stars at its heart."},
  {id:"M43", n:"De Mairan's Nebula",  ra:5.593,  dec:-5.27, mag:9.0, type:"nebula",    con:"Ori", note:"The detached northern lobe of the Orion Nebula, wrapped around its own star."},
  {id:"M44", n:"Beehive Cluster",     ra:8.667,  dec:19.67, mag:3.7, type:"open",       con:"Cnc", note:"A sprawling open cluster, naked-eye as a misty patch. Gorgeous in binoculars or a low-power eyepiece."},
  {id:"M45", n:"Pleiades",            ra:3.790,  dec:24.10, mag:1.6, type:"open",       con:"Tau", note:"The Seven Sisters. A brilliant young open cluster — best at low power so the whole group fits in the field."},
  {id:"M46", n:"M46 (open cluster)",  ra:7.696,  dec:-14.81,mag:6.1, type:"open",       con:"Pup", note:"A rich, even cluster with a bonus: planetary nebula NGC 2438 floats in front of it."},
  {id:"M47", n:"M47 (open cluster)",  ra:7.610,  dec:-14.48,mag:4.4, type:"open",       con:"Pup", note:"Bright and coarse — shares a low-power field with its subtler twin M46."},
  {id:"M48", n:"M48 (open cluster)",  ra:8.229,  dec:-5.75, mag:5.8, type:"open",       con:"Hya", note:"A big triangular cluster — Messier logged its position wrong; this is the real one."},
  {id:"M49", n:"M49 (galaxy)",        ra:12.497, dec:8.00,  mag:8.4, type:"galaxy",    con:"Vir", note:"The brightest elliptical of the Virgo Cluster — a soft round glow."},
  {id:"M50", n:"M50 (open cluster)",  ra:7.044,  dec:-8.34, mag:5.9, type:"open",       con:"Mon", note:"A heart-shaped cluster between Sirius and Procyon."},
  {id:"M51", n:"Whirlpool Galaxy",    ra:13.498, dec:47.20, mag:8.4, type:"galaxy",    con:"CVn", note:"A face-on spiral with a small companion. Under dark skies a 200mm scope hints at its curving arms."},
  {id:"M52", n:"M52 (open cluster)",  ra:23.413, dec:61.59, mag:6.9, type:"open",       con:"Cas", note:"A rich autumn cluster off the Cassiopeia W; the Bubble Nebula lurks nearby."},
  {id:"M53", n:"M53 (globular)",      ra:13.215, dec:18.17, mag:7.6, type:"globular",  con:"Com", note:"A compact globular near Diadem — a fuzzy snowball at low power."},
  {id:"M54", n:"M54 (globular)",      ra:18.918, dec:-30.48,mag:7.6, type:"globular",  con:"Sgr", note:"Dense and remote — it actually belongs to a dwarf galaxy being devoured by ours. Very low from Belgium."},
  {id:"M55", n:"M55 (globular)",      ra:19.667, dec:-30.96,mag:6.3, type:"globular",  con:"Sgr", note:"Big and loose, but very low from northern Europe — a southern-horizon challenge."},
  {id:"M56", n:"M56 (globular)",      ra:19.276, dec:30.18, mag:8.3, type:"globular",  con:"Lyr", note:"A modest globular midway between Albireo and Sulafat."},
  {id:"M57", n:"Ring Nebula",         ra:18.893, dec:33.03, mag:8.8, type:"planetary", con:"Lyr", note:"A dying star's smoke ring, neatly framed between two stars of Lyra. Small but unmistakable at higher power."},
  {id:"M58", n:"M58 (galaxy)",        ra:12.629, dec:11.82, mag:9.7, type:"galaxy",    con:"Vir", note:"A barred spiral in the heart of the Virgo Cluster."},
  {id:"M59", n:"M59 (galaxy)",        ra:12.700, dec:11.65, mag:9.6, type:"galaxy",    con:"Vir", note:"An elliptical sharing the eyepiece with M60 — a Virgo two-for-one."},
  {id:"M60", n:"M60 (galaxy)",        ra:12.728, dec:11.55, mag:8.8, type:"galaxy",    con:"Vir", note:"A bright elliptical; look for faint companion NGC 4647 touching it."},
  {id:"M61", n:"M61 (galaxy)",        ra:12.365, dec:4.47,  mag:9.7, type:"galaxy",    con:"Vir", note:"A face-on spiral in the southern reaches of the Virgo Cluster."},
  {id:"M62", n:"M62 (globular)",      ra:17.020, dec:-30.11,mag:6.5, type:"globular",  con:"Oph", note:"A lopsided globular, very low in the south."},
  {id:"M63", n:"Sunflower Galaxy",    ra:13.264, dec:42.03, mag:8.6, type:"galaxy",    con:"CVn", note:"A bright flocculent spiral below the Big Dipper's handle."},
  {id:"M64", n:"Black Eye Galaxy",    ra:12.945, dec:21.68, mag:8.5, type:"galaxy",    con:"Com", note:"A bright spiral with a dark dust arc over its core — the 'black eye' shows at 150×."},
  {id:"M65", n:"M65 (Leo Triplet)",   ra:11.315, dec:13.09, mag:9.3, type:"galaxy",    con:"Leo", note:"One of the Leo Triplet — two Messier galaxies plus NGC 3628 in one field."},
  {id:"M66", n:"M66 (Leo Triplet)",   ra:11.337, dec:12.99, mag:8.9, type:"galaxy",    con:"Leo", note:"The brighter half of the Leo Triplet pair, with a visibly asymmetric glow."},
  {id:"M67", n:"M67 (open cluster)",  ra:8.856,  dec:11.81, mag:6.1, type:"open",       con:"Cnc", note:"One of the oldest open clusters known (~4 billion years) — rich and compact."},
  {id:"M68", n:"M68 (globular)",      ra:12.658, dec:-26.74,mag:7.8, type:"globular",  con:"Hya", note:"A southern globular below Corvus; low but doable in spring."},
  {id:"M69", n:"M69 (globular)",      ra:18.523, dec:-32.35,mag:7.6, type:"globular",  con:"Sgr", note:"A small Teapot globular — extremely low from Belgium."},
  {id:"M70", n:"M70 (globular)",      ra:18.720, dec:-32.30,mag:7.9, type:"globular",  con:"Sgr", note:"M69's twin a degree east — same low-horizon challenge."},
  {id:"M71", n:"M71 (globular)",      ra:19.896, dec:18.78, mag:8.2, type:"globular",  con:"Sge", note:"A loose globular inside Sagitta's arrow shaft — long mistaken for an open cluster."},
  {id:"M72", n:"M72 (globular)",      ra:20.891, dec:-12.54,mag:9.3, type:"globular",  con:"Aqr", note:"Small and dim — one of the tougher Messier globulars."},
  {id:"M73", n:"M73 (asterism)",      ra:20.982, dec:-12.63,mag:8.9, type:"open",       con:"Aqr", note:"Just four unrelated stars in a Y — another checklist oddity, near M72."},
  {id:"M74", n:"M74 (galaxy)",        ra:1.611,  dec:15.78, mag:9.4, type:"galaxy",    con:"Psc", note:"A ghostly face-on spiral — famously the hardest Messier object; needs dark, transparent skies."},
  {id:"M75", n:"M75 (globular)",      ra:20.101, dec:-21.92,mag:8.5, type:"globular",  con:"Sgr", note:"Distant and very condensed — a tight little ball of light."},
  {id:"M76", n:"Little Dumbbell",     ra:1.705,  dec:51.57, mag:10.1,type:"planetary", con:"Per", note:"A small two-lobed planetary — the faintest Messier, but high in the sky; use 150×+."},
  {id:"M77", n:"M77 (galaxy)",        ra:2.712,  dec:-0.01, mag:8.9, type:"galaxy",    con:"Cet", note:"A Seyfert spiral with a bright star-like core, near Delta Ceti."},
  {id:"M78", n:"M78 (nebula)",        ra:5.779,  dec:0.08,  mag:8.3, type:"nebula",    con:"Ori", note:"A comet-like reflection nebula north of Orion's Belt — two stars in fog."},
  {id:"M79", n:"M79 (globular)",      ra:5.403,  dec:-24.52,mag:7.7, type:"globular",  con:"Lep", note:"A rare winter globular, below Orion in Lepus."},
  {id:"M80", n:"M80 (globular)",      ra:16.284, dec:-22.98,mag:7.3, type:"globular",  con:"Sco", note:"A very dense little globular between Antares and Graffias."},
  {id:"M81", n:"Bode's Galaxy",       ra:9.926,  dec:69.07, mag:6.9, type:"galaxy",    con:"UMa", note:"A bright spiral galaxy that shares the field with M82, the Cigar Galaxy — two galaxies in one view."},
  {id:"M82", n:"Cigar Galaxy",        ra:9.931,  dec:69.68, mag:8.4, type:"galaxy",    con:"UMa", note:"An edge-on starburst galaxy — a spindle of light in the same field as M81."},
  {id:"M83", n:"Southern Pinwheel",   ra:13.617, dec:-29.87,mag:7.5, type:"galaxy",    con:"Hya", note:"A bright face-on spiral, but very low from Belgium — a southern-horizon prize."},
  {id:"M84", n:"M84 (galaxy)",        ra:12.417, dec:12.89, mag:9.1, type:"galaxy",    con:"Vir", note:"Start of Markarian's Chain — an elliptical paired with M86 in one field."},
  {id:"M85", n:"M85 (galaxy)",        ra:12.423, dec:18.19, mag:9.1, type:"galaxy",    con:"Com", note:"The Virgo Cluster's northern outpost — a smooth lens of light."},
  {id:"M86", n:"M86 (galaxy)",        ra:12.437, dec:12.95, mag:8.9, type:"galaxy",    con:"Vir", note:"Sits beside M84 amid Markarian's Chain — sweep slowly, galaxies everywhere."},
  {id:"M87", n:"Virgo A",             ra:12.514, dec:12.39, mag:8.6, type:"galaxy",    con:"Vir", note:"The Virgo Cluster's giant elliptical — home of the first-ever photographed black hole."},
  {id:"M88", n:"M88 (galaxy)",        ra:12.533, dec:14.42, mag:9.6, type:"galaxy",    con:"Com", note:"A tilted multi-arm spiral in the thick of the cluster."},
  {id:"M89", n:"M89 (galaxy)",        ra:12.594, dec:12.56, mag:9.8, type:"galaxy",    con:"Vir", note:"A near-perfectly round elliptical."},
  {id:"M90", n:"M90 (galaxy)",        ra:12.614, dec:13.16, mag:9.5, type:"galaxy",    con:"Vir", note:"A large tilted spiral just north of M89."},
  {id:"M91", n:"M91 (galaxy)",        ra:12.590, dec:14.50, mag:10.2,type:"galaxy",    con:"Com", note:"A faint barred spiral — one of the dimmest Messiers; dark skies required."},
  {id:"M92", n:"M92 (globular)",      ra:17.285, dec:43.14, mag:6.4, type:"globular",  con:"Her", note:"Hercules' 'other' globular — superb, and unfairly overshadowed by M13."},
  {id:"M93", n:"M93 (open cluster)",  ra:7.742,  dec:-23.85,mag:6.2, type:"open",       con:"Pup", note:"A compact wedge-shaped cluster, low in the winter south."},
  {id:"M94", n:"M94 (galaxy)",        ra:12.849, dec:41.12, mag:8.2, type:"galaxy",    con:"CVn", note:"A bright, tight core that takes magnification well — easy for a galaxy."},
  {id:"M95", n:"M95 (galaxy)",        ra:10.732, dec:11.70, mag:9.7, type:"galaxy",    con:"Leo", note:"A barred spiral in the Leo I group, in one field with M96."},
  {id:"M96", n:"M96 (galaxy)",        ra:10.779, dec:11.82, mag:9.2, type:"galaxy",    con:"Leo", note:"The brightest of the Leo I trio (with M95 and M105)."},
  {id:"M97", n:"Owl Nebula",          ra:11.246, dec:55.02, mag:9.9, type:"planetary", con:"UMa", note:"A round planetary under the Big Dipper's bowl; the owl 'eyes' need dark skies and ~150×."},
  {id:"M98", n:"M98 (galaxy)",        ra:12.230, dec:14.90, mag:10.1,type:"galaxy",    con:"Com", note:"A near-edge-on sliver next to the star 6 Com — faint but distinctive."},
  {id:"M99", n:"M99 (galaxy)",        ra:12.313, dec:14.42, mag:9.9, type:"galaxy",    con:"Com", note:"A small face-on pinwheel just inside the cluster's edge."},
  {id:"M100",n:"M100 (galaxy)",       ra:12.382, dec:15.82, mag:9.3, type:"galaxy",    con:"Com", note:"One of the cluster's grandest spirals — a round glow with a brighter core."},
  {id:"M101",n:"Pinwheel Galaxy",     ra:14.053, dec:54.35, mag:7.9, type:"galaxy",    con:"UMa", note:"A large face-on spiral near the Big Dipper's handle. Big but diffuse — needs a dark sky."},
  {id:"M102",n:"Spindle Galaxy",      ra:15.108, dec:55.76, mag:9.9, type:"galaxy",    con:"Dra", note:"An edge-on lens with a dust lane (NGC 5866) — the usual identification of the disputed M102."},
  {id:"M103",n:"M103 (open cluster)", ra:1.556,  dec:60.66, mag:7.4, type:"open",       con:"Cas", note:"A small arrowhead of stars near Ruchbah, with a red giant at centre."},
  {id:"M104",n:"Sombrero Galaxy",     ra:12.667, dec:-11.62,mag:8.0, type:"galaxy",    con:"Vir", note:"An edge-on galaxy crossed by a dark dust lane, like a hat brim. Sits low in spring evenings."},
  {id:"M105",n:"M105 (galaxy)",       ra:10.797, dec:12.58, mag:9.3, type:"galaxy",    con:"Leo", note:"A round elliptical completing the Leo I trio."},
  {id:"M106",n:"M106 (galaxy)",       ra:12.316, dec:47.30, mag:8.4, type:"galaxy",    con:"CVn", note:"A big, bright tilted spiral — one of the easiest spring galaxies."},
  {id:"M107",n:"M107 (globular)",     ra:16.542, dec:-13.06,mag:7.9, type:"globular",  con:"Oph", note:"A loose globular south of Zeta Ophiuchi."},
  {id:"M108",n:"M108 (galaxy)",       ra:11.191, dec:55.67, mag:10.0,type:"galaxy",    con:"UMa", note:"A mottled edge-on streak — shares a low-power field with the Owl Nebula."},
  {id:"M109",n:"M109 (galaxy)",       ra:11.960, dec:53.37, mag:9.8, type:"galaxy",    con:"UMa", note:"A barred spiral right next to Phecda in the Dipper's bowl."},
  {id:"M110",n:"M110 (companion of M31)",ra:0.673,dec:41.69,mag:8.1, type:"galaxy",    con:"And", note:"M31's larger, fainter elliptical companion on the opposite side from M32."},
  {id:"NGC869",n:"Double Cluster",    ra:2.330,  dec:57.13, mag:4.3, type:"open",       con:"Per", note:"Two bright open clusters side by side in Perseus — a stunning low-power, wide-field sight."},
];

// Major annual meteor showers. Radiant in J2000 (RA hours, Dec deg); active window
// and peak as [month, day] (month 1-12). ZHR = zenithal hourly rate at peak.
export const SHOWERS = [
  {id:"quadrantids", n:"Quadrantids",    ra:15.30, dec:49.5,  from:[12,28], to:[1,12],  peak:[1,3],   zhr:110},
  {id:"lyrids",      n:"Lyrids",         ra:18.13, dec:33.6,  from:[4,14],  to:[4,30],  peak:[4,22],  zhr:18},
  {id:"etaAquariids",n:"Eta Aquariids",  ra:22.47, dec:-1.0,  from:[4,19],  to:[5,28],  peak:[5,6],   zhr:50},
  {id:"delAquariids",n:"Delta Aquariids",ra:22.70, dec:-16.3, from:[7,12],  to:[8,23],  peak:[7,30],  zhr:25},
  {id:"perseids",    n:"Perseids",       ra:3.20,  dec:58.0,  from:[7,17],  to:[8,24],  peak:[8,12],  zhr:100},
  {id:"orionids",    n:"Orionids",       ra:6.35,  dec:15.6,  from:[10,2],  to:[11,7],  peak:[10,21], zhr:20},
  {id:"leonids",     n:"Leonids",        ra:10.27, dec:21.8,  from:[11,6],  to:[11,30], peak:[11,17], zhr:15},
  {id:"geminids",    n:"Geminids",       ra:7.55,  dec:32.4,  from:[12,4],  to:[12,17], peak:[12,14], zhr:150},
  {id:"ursids",      n:"Ursids",         ra:14.47, dec:75.8,  from:[12,17], to:[12,26], peak:[12,22], zhr:10},
];

export const LOCATIONS = [
  {name:"Brugge, West-Flanders", lat:51.21, lon:3.22},
  {name:"Kortrijk, West-Flanders", lat:50.83, lon:3.27},
  {name:"Oostende (coast)", lat:51.23, lon:2.92},
  {name:"Brussels", lat:50.85, lon:4.35},
  {name:"Antwerp", lat:51.22, lon:4.40},
  {name:"Amsterdam", lat:52.37, lon:4.90},
  {name:"London", lat:51.51, lon:-0.13},
  {name:"Paris", lat:48.86, lon:2.35},
  {name:"Berlin", lat:52.52, lon:13.40},
  {name:"New York", lat:40.71, lon:-74.01},
  {name:"Los Angeles", lat:34.05, lon:-118.24},
  {name:"Sydney", lat:-33.87, lon:151.21},
];
